PUT http://localhost:8080/api/users HTTP/1.1

Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIxIiwiZXhwIjoxNzI0NTYwODMzLCJpYXQiOjE3MjQ0NzQ0MzN9.o4XI--283wmUqIJFUxHxpCPi4PXVvJ10SbBUFIAnex0"

body: 
{
  "email": "mike@bettercall.com",
  "password": "654321"
}